from .SprintDuplicateQuestionsPC import *
from .TwitterSemEval2015PC import *
from .TwitterURLCorpusPC import *
from .PAWSQQPPC import *
from .PAWSWikiPC import *
from .MRPCPC import *
from .QQPPC import *
from .FullTwitterSemEval2015PC import *
from .SemEvalArgSimPC import *